export const GOOGLE_MIGRATION = Object.freeze({
  "version": 2,
  "generatedAt": "2026-08-04T18:32:00+02:00",
  "sourceSheets": [
    {
      "title": "Gestione Reselling Professionale",
      "id": "12hiyA2UGh94oz_FyEpEjMZayi-kjZsLyBa2JdQX7Bwg"
    },
    {
      "title": "Vendite multipiattaforma 2026",
      "id": "1nBD0okk5EFpXg6CKbKa9J4qt03DaxYTU6LHcmUMTfG4"
    }
  ],
  "inventory": [
    {
      "id": "google-mod01",
      "code": "MOD01",
      "brand": "POLO",
      "title": "Camicia bianca con etichetta POLO",
      "category": "Camicia",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "Camicia bianca con etichetta della marca “POLO”. Annuncio accettato senza blocchi o segnalazioni sulle piattaforme utilizzate. L’accettazione da parte delle piattaforme non costituisce una verifica formale di autenticità. La conferma dell’assistenza Modori non è ancora arrivata. Condizioni registrate provvisorie.\n\nProssima azione: Attendere verifica autenticità / monitorare eventuali segnalazioni",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": false,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Attendere verifica autenticità / monitorare eventuali segnalazioni",
      "targetInferred": false,
      "targetSource": ""
    },
    {
      "id": "google-mod02",
      "code": "MOD02",
      "brand": "Polo Ralph Lauren",
      "title": "Polo bianca Custom Fit",
      "category": "Polo",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 15.0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "Capo lavato e controllato. Modello Polo by Ralph Lauren Custom Fit. Fotografie definitive e misure già realizzate. Venduto su Vinted a 15,00 €.",
      "sale": {
        "platform": "Vinted",
        "price": 15.0,
        "net": 15.0,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": 18.9,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo annuncio"
    },
    {
      "id": "google-mod03",
      "code": "MOD03",
      "brand": "Senza marca",
      "title": "T-shirt bianca Tommy Jeans",
      "category": "Altro",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 8.0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted"
      ],
      "notes": "T-shirt bianca Tommy Jeans con ingiallimento presente sul collo. Venduta su Vinted a 8,00 €.",
      "sale": {
        "platform": "Vinted",
        "price": 8.0,
        "net": 8.0,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": false,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo vendita"
    },
    {
      "id": "google-mod04",
      "code": "MOD04",
      "brand": "Reebok Classic",
      "title": "Pantaloncini bianchi Reebok Classic",
      "category": "Shorts",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [],
      "notes": "",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": false,
      "targetSource": ""
    },
    {
      "id": "google-mod05",
      "code": "MOD05",
      "brand": "Ralph Lauren",
      "title": "T-shirt scura con pony ricamato",
      "category": "T-shirt",
      "size": "L",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 20.0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "T-shirt di colore scuro con piccolo pony ricamato chiaro sul petto. Etichetta Ralph Lauren taglia L visibilmente usurata e sfilacciata. Capo lavato e controllato. Fotografie definitive e misure già realizzate. Venduto su eBay a 18,91 €.",
      "sale": {
        "platform": "eBay",
        "price": 18.91,
        "net": 18.91,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": 24.9,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo annuncio"
    },
    {
      "id": "google-mod06",
      "code": "MOD06",
      "brand": "Polo Ralph Lauren",
      "title": "Polo nera Ralph Lauren Made in USA",
      "category": "Polo",
      "size": "S",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 20.0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "Capo lavato e controllato. Nessun difetto strutturale rilevante riscontrato nel controllo finale. Fotografie definitive e misure già realizzate. Pubblicato su tutte le piattaforme gestite.",
      "sale": {
        "platform": "Vinted",
        "price": 23.9,
        "net": 23.9,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": 24.9,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo annuncio"
    },
    {
      "id": "google-mod07",
      "code": "MOD07",
      "brand": "U.S. Polo Assn.",
      "title": "Polo nera con dettagli viola e patch numero 3",
      "category": "Polo",
      "size": "S",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 15.0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "Polo nera con dettagli viola, ricamo viola sul petto e patch viola con numero 3 sulla manica. Capo lavato e controllato. Fotografie definitive e misure già realizzate. Pubblicato su tutte le piattaforme gestite.",
      "sale": {
        "platform": "Vinted",
        "price": 15.0,
        "net": 15.0,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": 18.9,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo annuncio"
    },
    {
      "id": "google-mod08",
      "code": "MOD08",
      "brand": "Adidas",
      "title": "Pantaloncini sportivi blu Adidas ClimaLite",
      "category": "Shorts",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [],
      "notes": "Tecnologia / dicitura ClimaLite.",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": false,
      "targetSource": ""
    },
    {
      "id": "google-mod09",
      "code": "MOD09",
      "brand": "Senza marca",
      "title": "Pantaloni lunghi Australian",
      "category": "Altro",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 20.0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted"
      ],
      "notes": "Pantaloni lunghi Australian. Venduti su Vinted a 20,00 €.",
      "sale": {
        "platform": "Vinted",
        "price": 20.0,
        "net": 20.0,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": false,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo vendita"
    },
    {
      "id": "google-mod10",
      "code": "MOD10",
      "brand": "Senza marca",
      "title": "Camicia Tommy Hilfiger con macchia",
      "category": "Altro",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 9.9,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted"
      ],
      "notes": "Camicia Tommy Hilfiger con macchia. Venduta su Vinted a 9,90 €.",
      "sale": {
        "platform": "Vinted",
        "price": 9.9,
        "net": 9.9,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": false,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo vendita"
    },
    {
      "id": "google-mod11",
      "code": "MOD11",
      "brand": "G.A.P. Company",
      "title": "Camicia floreale",
      "category": "Camicia",
      "size": "M",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 32.5,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "Camicia con fantasia floreale. Capo lavato e controllato. Fotografie definitive e misure già realizzate. Pubblicato su tutte le piattaforme gestite.",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": 39.9,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo annuncio"
    },
    {
      "id": "google-mod12",
      "code": "MOD12",
      "brand": "Senza marca",
      "title": "Bermuda cargo Carhartt",
      "category": "Altro",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 30.9,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted"
      ],
      "notes": "",
      "sale": {
        "platform": "Vinted",
        "price": 30.9,
        "net": 30.9,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": false,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo vendita"
    },
    {
      "id": "google-mod13",
      "code": "MOD13",
      "brand": "Polo Ralph Lauren",
      "title": "Polo gialla a fasce con ricamo",
      "category": "Polo",
      "size": "M",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 17.5,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [
        "Vinted",
        "eBay",
        "Wallapop",
        "Subito",
        "Depop"
      ],
      "notes": "Polo gialla con etichetta Polo by Ralph Lauren, taglia M e dicitura Made in Thailand. Presenta fasce orizzontali nere e bianche, grande ricamo nero sul petto e patch con numero 3 sulla manica. Capo lavato e controllato. Fotografie definitive e misure già realizzate. Pubblicato su tutte le piattaforme gestite.",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": 21.9,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo annuncio"
    },
    {
      "id": "google-mod14",
      "code": "MOD14",
      "brand": "Senza marca",
      "title": "Gilet smanicato Tommy beige",
      "category": "Altro",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 15.9,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "sold",
      "platforms": [
        "Vinted"
      ],
      "notes": "Gilet smanicato Tommy beige. Venduto su Vinted a 15,90 €.",
      "sale": {
        "platform": "Vinted",
        "price": 15.9,
        "net": 15.9,
        "date": "",
        "currency": "EUR"
      },
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": false,
      "removedElsewhere": true,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": true,
      "targetSource": "prezzo vendita"
    },
    {
      "id": "google-mod15",
      "code": "MOD15",
      "brand": "Levi’s",
      "title": "T-shirt color mattone Levi’s",
      "category": "T-shirt",
      "size": "",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [],
      "notes": "",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": false,
      "targetSource": ""
    },
    {
      "id": "google-mod16",
      "code": "MOD16",
      "brand": "Lacoste",
      "title": "Polo rossa Lacoste",
      "category": "Polo",
      "size": "8",
      "condition": "Ottime",
      "cost": 8.44,
      "target": 0,
      "source": "Modori",
      "purchaseDate": "2026-07-20",
      "status": "live",
      "platforms": [],
      "notes": "",
      "sale": null,
      "createdAt": "2026-07-20T12:00:00.000Z",
      "updatedAt": "2026-08-04T12:00:00.000Z",
      "lotCode": "MOD-0001",
      "costProvisional": true,
      "listingPrice": null,
      "minimumPrice": null,
      "photosDone": true,
      "removedElsewhere": false,
      "lastPriceDrop": "",
      "nextAction": "Nessuna",
      "targetInferred": false,
      "targetSource": ""
    }
  ],
  "salesHistory": [
    {
      "id": "hist-001",
      "date": "2026-01-17",
      "platform": "Vinted",
      "title": "Lotto carte MTG",
      "price": 7.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-002",
      "date": "2026-01-21",
      "platform": "Vinted",
      "title": "Portafoglio marrone",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-003",
      "date": "2026-01-31",
      "platform": "Vinted",
      "title": "Lotto Lamincards Dragon Ball",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-004",
      "date": "2026-02-03",
      "platform": "Vinted",
      "title": "Gilet sartoriale",
      "price": 20.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-005",
      "date": "2026-02-03",
      "platform": "Vinted",
      "title": "Zaino GHANA 50",
      "price": 25.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-006",
      "date": "2026-02-08",
      "platform": "eBay",
      "title": "Set Inter FC Puzzle 1000 pezzi + Sciarpa",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-007",
      "date": "2026-02-10",
      "platform": "Vinted",
      "title": "Camicia Piazza Italia",
      "price": 5.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-008",
      "date": "2026-02-14",
      "platform": "eBay",
      "title": "Maglione donna Fair Isle lurex S/M",
      "price": 18.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-009",
      "date": "2026-02-18",
      "platform": "Vinted",
      "title": "Sciarpa marrone",
      "price": 8.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-010",
      "date": "2026-02-19",
      "platform": "Vinted",
      "title": "Sciarpa vintage",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-011",
      "date": "2026-02-19",
      "platform": "Wallapop",
      "title": "Gilet Fiorella Rubino",
      "price": 10.5,
      "country": "Spagna",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-012",
      "date": "2026-02-20",
      "platform": "Vinted",
      "title": "Giacca Off Shore Ocean Winds",
      "price": 23.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-013",
      "date": "2026-02-22",
      "platform": "Vinted",
      "title": "Sciarpa rossa",
      "price": 6.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-014",
      "date": "2026-02-28",
      "platform": "Vinted",
      "title": "Camicia Double B Brian & Barry",
      "price": 14.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-015",
      "date": "2026-03-02",
      "platform": "Vinted",
      "title": "Forbici ricamo cicogna",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-016",
      "date": "2026-03-02",
      "platform": "eBay",
      "title": "Giubbotto Ellen Rose blu M",
      "price": 13.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-017",
      "date": "2026-03-04",
      "platform": "Vinted",
      "title": "Top OVS",
      "price": 4.6,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-018",
      "date": "2026-03-04",
      "platform": "Vinted",
      "title": "Camicia Belfe & Belfe uomo",
      "price": 7.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-019",
      "date": "2026-03-12",
      "platform": "Vinted",
      "title": "Sandali Guya Ferri",
      "price": 8.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-020",
      "date": "2026-03-13",
      "platform": "Vinted",
      "title": "Camicia Camicissima",
      "price": 9.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-021",
      "date": "2026-03-13",
      "platform": "Vinted",
      "title": "Camicia Piombo",
      "price": 10.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-022",
      "date": "2026-03-13",
      "platform": "Vinted",
      "title": "Nike Air More Uptempo 96",
      "price": 35.0,
      "country": "Portogallo",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-023",
      "date": "2026-03-15",
      "platform": "eBay",
      "title": "Set manicure BIBA London 5 pezzi",
      "price": 11.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-024",
      "date": "2026-03-16",
      "platform": "Vinted",
      "title": "Stivali Lionelle",
      "price": 13.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-025",
      "date": "2026-03-16",
      "platform": "Vinted",
      "title": "Arcolaio Yarn Swift",
      "price": 23.2,
      "country": "Portogallo",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-026",
      "date": "2026-03-16",
      "platform": "Wallapop",
      "title": "Beauty Case Donatella",
      "price": 4.0,
      "country": "Spagna",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-027",
      "date": "2026-03-19",
      "platform": "Vinted",
      "title": "Zaino Gormiti",
      "price": 6.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-028",
      "date": "2026-03-19",
      "platform": "Vinted",
      "title": "Scarpe ballo Antares",
      "price": 40.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-029",
      "date": "2026-03-20",
      "platform": "Vinted",
      "title": "Gilet MAPS Girl",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-030",
      "date": "2026-03-20",
      "platform": "Vinted",
      "title": "Camicia Pierre Cardin",
      "price": 10.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-031",
      "date": "2026-03-20",
      "platform": "Wallapop",
      "title": "Vestaglia Veronique",
      "price": 8.0,
      "country": "Spagna",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-032",
      "date": "2026-03-22",
      "platform": "Vinted",
      "title": "Sneakers Skechers Cordona",
      "price": 39.5,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-033",
      "date": "2026-03-23",
      "platform": "Vinted",
      "title": "Décolleté Graceland",
      "price": 7.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-034",
      "date": "2026-03-23",
      "platform": "Wallapop",
      "title": "Giacca Blauer USA",
      "price": 35.0,
      "country": "Spagna",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-035",
      "date": "2026-03-24",
      "platform": "eBay",
      "title": "Macchina Popcorn Ariete Party Time 2957",
      "price": 24.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-036",
      "date": "2026-03-26",
      "platform": "Vinted",
      "title": "Décolleté Hot Ice",
      "price": 10.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-037",
      "date": "2026-03-27",
      "platform": "Vinted",
      "title": "Felpa Liu Jo Sport",
      "price": 25.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-038",
      "date": "2026-03-27",
      "platform": "Wallapop",
      "title": "Blazer blu navy",
      "price": 15.4,
      "country": "Spagna",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-039",
      "date": "2026-03-28",
      "platform": "Vestiaire Collective",
      "title": "Sciarpa Ermenegildo Zegna",
      "price": 36.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-040",
      "date": "2026-03-29",
      "platform": "eBay",
      "title": "Maglia Juventus 2011/2012 Nike Dri-FIT bambino L",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-041",
      "date": "2026-03-31",
      "platform": "Vinted",
      "title": "Camicia Luca D'Altieri",
      "price": 6.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-042",
      "date": "2026-04-02",
      "platform": "Vinted",
      "title": "Giacca Terranova",
      "price": 6.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-043",
      "date": "2026-04-02",
      "platform": "Vinted",
      "title": "Zaino Leopard",
      "price": 6.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-044",
      "date": "2026-04-08",
      "platform": "Vinted",
      "title": "T-shirt Puma",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-045",
      "date": "2026-04-08",
      "platform": "Vinted",
      "title": "Sneakers Skechers",
      "price": 18.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-046",
      "date": "2026-04-08",
      "platform": "Vinted",
      "title": "Occhiali Fendi",
      "price": 57.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-047",
      "date": "2026-04-09",
      "platform": "Vinted",
      "title": "Macchina da scrivere Remington",
      "price": 25.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-048",
      "date": "2026-04-11",
      "platform": "eBay",
      "title": "Pile Lotto vintage blu L full zip",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-049",
      "date": "2026-04-11",
      "platform": "eBay",
      "title": "Polo Moncler bianca XL",
      "price": 25.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-050",
      "date": "2026-04-14",
      "platform": "Vinted",
      "title": "Abito Desigual",
      "price": 20.0,
      "country": "Austria",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-051",
      "date": "2026-04-15",
      "platform": "Vinted",
      "title": "T-shirt Insane Stone",
      "price": 9.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-052",
      "date": "2026-04-17",
      "platform": "Vinted",
      "title": "Foulard seta paisley",
      "price": 9.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-053",
      "date": "2026-04-20",
      "platform": "Vinted",
      "title": "Ferro Rowenta Pro Master",
      "price": 18.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-054",
      "date": "2026-04-21",
      "platform": "Vinted",
      "title": "T-shirt The City of Palms",
      "price": 5.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-055",
      "date": "2026-04-21",
      "platform": "Vinted",
      "title": "Sneakers Enrico Coveri",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-056",
      "date": "2026-04-22",
      "platform": "Vinted",
      "title": "Top OVS",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-057",
      "date": "2026-04-24",
      "platform": "Vinted",
      "title": "Blazer Steve Collins",
      "price": 7.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-058",
      "date": "2026-04-25",
      "platform": "Vinted",
      "title": "Top Tezenis",
      "price": 2.9,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-059",
      "date": "2026-04-29",
      "platform": "Vinted",
      "title": "Bomber Beyond",
      "price": 22.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-060",
      "date": "2026-05-05",
      "platform": "Vinted",
      "title": "Maglia Griffe Tricot",
      "price": 7.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-061",
      "date": "2026-05-06",
      "platform": "Vinted",
      "title": "Maglia leopardata",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-062",
      "date": "2026-05-07",
      "platform": "Vinted",
      "title": "Cardigan Conbipel",
      "price": 6.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-063",
      "date": "2026-05-07",
      "platform": "Vinted",
      "title": "Giacca Moonstone",
      "price": 20.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-064",
      "date": "2026-05-08",
      "platform": "Vinted",
      "title": "T-shirt X-Name nera",
      "price": 3.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-065",
      "date": "2026-05-09",
      "platform": "Vinted",
      "title": "T-shirt Terranova",
      "price": 11.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-066",
      "date": "2026-05-09",
      "platform": "Vinted",
      "title": "Borsa Serapian",
      "price": 54.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-067",
      "date": "2026-05-13",
      "platform": "Vinted",
      "title": "T-shirt X-Name bianca",
      "price": 3.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-068",
      "date": "2026-05-13",
      "platform": "Vinted",
      "title": "Blusa Motivi",
      "price": 8.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-069",
      "date": "2026-05-14",
      "platform": "Vinted",
      "title": "T-shirt Calvin Klein",
      "price": 3.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-070",
      "date": "2026-05-18",
      "platform": "eBay",
      "title": "Sneakers Jordan Max Aura 3 EU45",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-071",
      "date": "2026-05-21",
      "platform": "Vinted",
      "title": "Canotta Motivi",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-072",
      "date": "2026-05-22",
      "platform": "Vinted",
      "title": "Jeans Armani Jeans",
      "price": 20.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-073",
      "date": "2026-05-22",
      "platform": "Vinted",
      "title": "Pareo verde lime",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-074",
      "date": "2026-05-23",
      "platform": "Vinted",
      "title": "Canotta Tezenis",
      "price": 3.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-075",
      "date": "2026-05-23",
      "platform": "Vinted",
      "title": "Maglia Zara",
      "price": 7.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-076",
      "date": "2026-05-26",
      "platform": "Vinted",
      "title": "Pareo verde sfumato",
      "price": 4.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-077",
      "date": "2026-05-26",
      "platform": "Vinted",
      "title": "Top smanicato floreale",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-078",
      "date": "2026-05-28",
      "platform": "Vinted",
      "title": "Blusa Double Face",
      "price": 6.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-079",
      "date": "2026-05-28",
      "platform": "Vinted",
      "title": "Top canotta floreale",
      "price": 4.0,
      "country": "Germania",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-080",
      "date": "2026-05-28",
      "platform": "Vinted",
      "title": "Gonna Antonello Serio",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-081",
      "date": "2026-05-29",
      "platform": "Vinted",
      "title": "Gonna OVS",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-082",
      "date": "2026-05-30",
      "platform": "Vinted",
      "title": "Abito New Collection",
      "price": 9.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-083",
      "date": "2026-05-31",
      "platform": "Vinted",
      "title": "Blazer nero glitter",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-084",
      "date": "2026-05-31",
      "platform": "eBay",
      "title": "Apple iPad Air 2 Wi-Fi 16 GB A1566",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-085",
      "date": "2026-06-01",
      "platform": "Vinted",
      "title": "Pantaloni culottes Siste's",
      "price": 10.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-086",
      "date": "2026-06-03",
      "platform": "Subito",
      "title": "Borsa Fotografica Case Logic Nera",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-087",
      "date": "2026-06-03",
      "platform": "Vinted",
      "title": "Bolero Conbipel",
      "price": 5.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-088",
      "date": "2026-06-05",
      "platform": "Vinted",
      "title": "T-shirt Coca-Cola",
      "price": 3.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-089",
      "date": "2026-06-06",
      "platform": "Vinted",
      "title": "Maglia H&M",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-090",
      "date": "2026-06-06",
      "platform": "Vinted",
      "title": "Pantaloni Gladys",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-091",
      "date": "2026-06-07",
      "platform": "Vinted",
      "title": "Borsa tracolla Fantasy",
      "price": 7.2,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-092",
      "date": "2026-06-08",
      "platform": "Vinted",
      "title": "Maglia OVS",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-093",
      "date": "2026-06-08",
      "platform": "Vinted",
      "title": "T-shirt X-Name grigia",
      "price": 7.2,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-094",
      "date": "2026-06-09",
      "platform": "Vinted",
      "title": "Pantaloni DEB & 59",
      "price": 4.8,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-095",
      "date": "2026-06-10",
      "platform": "Vinted",
      "title": "Cardigan Intimissimi",
      "price": 10.35,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-096",
      "date": "2026-06-10",
      "platform": "Vinted",
      "title": "Collana etnica",
      "price": 4.8,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-097",
      "date": "2026-06-10",
      "platform": "Vinted",
      "title": "Custodia Samsonite",
      "price": 6.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-098",
      "date": "2026-06-11",
      "platform": "Vinted",
      "title": "Gilet Lotto",
      "price": 13.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-099",
      "date": "2026-06-13",
      "platform": "Vinted",
      "title": "Pareo rosa fucsia",
      "price": 3.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-100",
      "date": "2026-06-14",
      "platform": "Vinted",
      "title": "Cardigan nero",
      "price": 5.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-101",
      "date": "2026-06-15",
      "platform": "Vinted",
      "title": "Costume Julipet",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-102",
      "date": "2026-06-16",
      "platform": "Vinted",
      "title": "Cardigan Fanatique",
      "price": 7.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-103",
      "date": "2026-06-17",
      "platform": "Vinted",
      "title": "Pantaloni Gladys",
      "price": 4.8,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-104",
      "date": "2026-06-17",
      "platform": "Vinted",
      "title": "Maglia termica Brugi",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-105",
      "date": "2026-06-18",
      "platform": "Vinted",
      "title": "Tunica Motivi",
      "price": 6.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-106",
      "date": "2026-06-18",
      "platform": "Vinted",
      "title": "Foulard seta",
      "price": 11.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-107",
      "date": "2026-06-22",
      "platform": "Vestiaire Collective",
      "title": "Giubbotto Non Signé",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-108",
      "date": "2026-06-23",
      "platform": "Vinted",
      "title": "Costume Ragno Beachwear",
      "price": 8.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-109",
      "date": "2026-06-26",
      "platform": "Vinted",
      "title": "Pareo floreale turchese",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-110",
      "date": "2026-06-27",
      "platform": "Vinted",
      "title": "Pareo lavanda",
      "price": 13.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-111",
      "date": "2026-06-27",
      "platform": "Subito",
      "title": "Shell F1 Zaino Racing Rosso Ricamato",
      "price": 15.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-112",
      "date": "2026-06-30",
      "platform": "Vinted",
      "title": "Occhiali Avon Arras",
      "price": 4.8,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-113",
      "date": "2026-06-30",
      "platform": "Vinted",
      "title": "Set 2 articoli (Pareo maxi floreale + Pareo fantasia astratta)",
      "price": 10.0,
      "country": "Francia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-114",
      "date": "2026-06-30",
      "platform": "Vinted",
      "title": "Top Tezenis leopardato",
      "price": 3.5,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-115",
      "date": "2026-06-30",
      "platform": "Vinted",
      "title": "Top floreale",
      "price": 4.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-116",
      "date": "2026-06-30",
      "platform": "Vinted",
      "title": "Pareo copricostume",
      "price": 5.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    },
    {
      "id": "hist-117",
      "date": "2026-06-30",
      "platform": "Vinted",
      "title": "Top Vicolo",
      "price": 6.0,
      "country": "Italia",
      "currency": "EUR",
      "source": "Vendite multipiattaforma 2026"
    }
  ],
  "business": {
    "lots": [
      {
        "code": "MOD-0001",
        "purchaseDate": "2026-07-05",
        "supplier": "Modori",
        "quantity": 16,
        "goodsCost": 195.0,
        "purchaseCosts": 0.0,
        "grossCost": 195.0,
        "receivedDate": "2026-07-20",
        "status": "Ricevuto",
        "refund": 60.0,
        "refundStatus": "Accreditato",
        "netCost": 135.0,
        "provisionalUnitCost": 8.44,
        "soldItems": 9,
        "registeredRevenue": 157.51,
        "notes": "Rimborso Modori di 60,00 € accreditato sul metodo di pagamento originale; costo netto 135,00 € e media provvisoria 8,44 € su 16 articoli. Condizioni contestate provvisorie fino al controllo post-lavaggio. MOD01: articolo pubblicato; annuncio accettato senza blocchi o segnalazioni, ma l’accettazione delle piattaforme non costituisce una verifica formale di autenticità e la conferma dell’assistenza Modori non è ancora arrivata."
      }
    ],
    "suppliers": [
      {
        "name": "Modori",
        "site": "modori.it",
        "order": "BrandBox - 15 articoli / estivo",
        "orderDate": "2026-07-05",
        "grossCost": 195.0,
        "orderedItems": 15,
        "receivedItems": 16,
        "soldItems": 9,
        "revenue": 157.51,
        "status": "Ricevuto",
        "refund": 60.0,
        "refundStatus": "Accreditato",
        "netCost": 135.0,
        "provisionalUnitCost": 8.44,
        "notes": "Ordine ricevuto in ritardo il 20/07/2026. Ricevuti 16 articoli rispetto ai 15 ordinati. Al momento 6 articoli risultano conformi e lavorabili, mentre 10 articoli sono oggetto di contestazione. Reclamo aperto con il fornitore. Rimborso di 60,00 € accreditato sul metodo di pagamento originale; costo netto 135,00 € e media netta provvisoria 8,44 € su 16 articoli. Non calcolare ancora la percentuale definitiva di articoli vendibili, il costo medio vendibile o una valutazione finale del fornitore. Le condizioni dei capi contestati restano provvisorie fino al controllo post-lavaggio. MOD01: articolo pubblicato; annuncio accettato senza blocchi o segnalazioni, ma l’accettazione delle piattaforme non costituisce una verifica formale di autenticità e la conferma dell’assistenza Modori non è ancora arrivata."
      }
    ],
    "expenses": [
      {
        "date": "",
        "category": "Attrezzatura",
        "description": "iPhone 17 Pro nuovo acquistato per l’attività",
        "amount": 1184.87
      }
    ],
    "checklist": [
      {
        "area": "Fisco",
        "task": "Commercialista definitivo",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Scegliere referente e farsi confermare per iscritto regime, ATECO, INPS, Camera di Commercio e SUAP.",
        "deadline": "Luglio"
      },
      {
        "area": "Fisco",
        "task": "Partita IVA e pratiche collegate",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Da fare solo dopo scelta commercialista.",
        "deadline": "Agosto"
      },
      {
        "area": "Fisco",
        "task": "PEC / firma digitale o delega",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Serve per pratiche e comunicazioni ufficiali.",
        "deadline": "Agosto"
      },
      {
        "area": "Vinted Pro",
        "task": "Profilo Vinted Pro",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Attivare quando l'attività è pronta fiscalmente.",
        "deadline": "Agosto / settembre"
      },
      {
        "area": "Documenti",
        "task": "Sistema prove d'acquisto",
        "status": "In corso",
        "priority": "Alta",
        "notes": "Conservare ordine, pagamento, fattura/ricevuta e screenshot del lotto.",
        "deadline": "Luglio"
      },
      {
        "area": "Fornitori",
        "task": "Box Modori ordinata",
        "status": "Fatto",
        "priority": "Alta",
        "notes": "Ordine effettuato e pagato. Pacco ricevuto il 20/07/2026. Contestazione aperta per 10 articoli.",
        "deadline": "Luglio"
      },
      {
        "area": "Fornitori",
        "task": "Ricezione box Modori",
        "status": "Fatto",
        "priority": "Alta",
        "notes": "Ricevuti 16 articoli il 20/07/2026 rispetto ai 15 ordinati.",
        "deadline": "Luglio"
      },
      {
        "area": "Magazzino",
        "task": "Controllo fisico capi",
        "status": "In corso",
        "priority": "Alta",
        "notes": "Prima verifica completata: 6 capi conformi e lavorabili, 10 capi contestati. Attendere l’esito del reclamo prima della chiusura definitiva.",
        "deadline": "Luglio"
      },
      {
        "area": "Magazzino",
        "task": "Articoli vendibili lotto",
        "status": "In corso",
        "priority": "Alta",
        "notes": "6 articoli attualmente confermati come conformi. Numero definitivo da stabilire dopo la risposta di Modori.",
        "deadline": "Luglio"
      },
      {
        "area": "ARTICOLI",
        "task": "Inserimento articoli singoli",
        "status": "In corso",
        "priority": "Alta",
        "notes": "Si possono inserire i 6 articoli conformi quando saranno disponibili marca, categoria, taglia, descrizione e stato. Non inserire ancora come vendibili i 10 articoli contestati.",
        "deadline": "Luglio"
      },
      {
        "area": "Foto",
        "task": "Workflow foto definitivo",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Formato 4:5, foto reali, fronte/retro/etichette/difetti.",
        "deadline": "Luglio"
      },
      {
        "area": "Misure",
        "task": "Schema misure capi",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Compilare misure principali per ridurre domande e resi.",
        "deadline": "Luglio"
      },
      {
        "area": "Spedizioni",
        "task": "Materiale imballaggio",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Buste, nastro, etichette, bilancia, rullo levapelucchi.",
        "deadline": "Luglio"
      },
      {
        "area": "Spedizioni",
        "task": "Stampante etichette",
        "status": "Da valutare",
        "priority": "Media",
        "notes": "Valutare acquisto prima di aumentare i volumi.",
        "deadline": "Agosto"
      },
      {
        "area": "Prezzi",
        "task": "Prezzo minimo per articolo",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Compilare colonna prezzo minimo prima di accettare offerte.",
        "deadline": "Luglio"
      },
      {
        "area": "Multicanale",
        "task": "Regola rimozione annunci",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Quando vendi su una piattaforma, rimuovere subito dalle altre.",
        "deadline": "Agosto"
      },
      {
        "area": "Messaggi",
        "task": "Template messaggi clienti",
        "status": "Da fare",
        "priority": "Bassa",
        "notes": "Preparare risposte per misure, trattative, spedizione, reso.",
        "deadline": "Agosto"
      },
      {
        "area": "Resi",
        "task": "Politica resi e reclami",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Da definire prima di Vinted Pro.",
        "deadline": "Agosto"
      },
      {
        "area": "Contabilità",
        "task": "Registrazione spese generali",
        "status": "In corso",
        "priority": "Media",
        "notes": "Inserire in SPESE ogni costo utile all'attività.",
        "deadline": "Luglio / agosto"
      },
      {
        "area": "Revisione",
        "task": "Controllo foglio dopo arrivo box",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Aggiornare LOTTI, FORNITORI e poi ARTICOLI.",
        "deadline": "Luglio"
      },
      {
        "area": "Brand",
        "task": "Nome profilo definitivo",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Chiudere nome unico per Vinted/Instagram, senza continuare a cambiare.",
        "deadline": "Luglio"
      },
      {
        "area": "Brand",
        "task": "Bio profilo e immagine/logo",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Preparare profilo pulito, credibile e coerente con reselling vintage/streetwear.",
        "deadline": "Luglio"
      },
      {
        "area": "Documenti",
        "task": "Cartella Drive ricevute e prove acquisto",
        "status": "In corso",
        "priority": "Alta",
        "notes": "Creare struttura per fatture, ricevute, screenshot ordini, pagamenti e documenti fiscali.",
        "deadline": "Luglio"
      },
      {
        "area": "Account",
        "task": "Email dedicata attività",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Meglio separare comunicazioni personali e attività.",
        "deadline": "Luglio"
      },
      {
        "area": "Account",
        "task": "Conto, sottoconto o carta separata",
        "status": "Da valutare",
        "priority": "Media",
        "notes": "Serve a non mischiare soldi personali, merce, costi e accantonamenti.",
        "deadline": "Agosto"
      },
      {
        "area": "Magazzino",
        "task": "Organizzazione armadio per zone",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Dividere: da controllare, da fotografare, pubblicato, venduto/da spedire, difettato.",
        "deadline": "Luglio"
      },
      {
        "area": "Magazzino",
        "task": "Codici fisici articolo",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Usare A001, A002, A003 e riportare lo stesso codice su foglio e posizione fisica.",
        "deadline": "Luglio"
      },
      {
        "area": "Spedizioni",
        "task": "Kit minimo spedizione pronto",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Metro, buste, nastro, etichette, pennarello, bilancia, leva-pelucchi.",
        "deadline": "Luglio"
      },
      {
        "area": "Foto",
        "task": "Set foto reale standard 4:5",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Stesso sfondo, stessa luce, copertina reale forte, niente differenze evidenti tra foto e capo.",
        "deadline": "Luglio"
      },
      {
        "area": "Descrizioni",
        "task": "Template titoli e descrizioni definitivo",
        "status": "In corso",
        "priority": "Media",
        "notes": "Preparare schema fisso per Vinted, Wallapop/Subito ed eBay.",
        "deadline": "Luglio"
      },
      {
        "area": "Fornitori",
        "task": "Test almeno secondo fornitore",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Non dipendere solo da Modori; testare almeno 2 fornitori entro agosto.",
        "deadline": "Agosto"
      },
      {
        "area": "Fornitori",
        "task": "Valutazione Modori dopo controllo e vendite",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Valutare qualità, difetti, articoli vendibili, costo medio reale e velocità vendita.",
        "deadline": "Agosto"
      },
      {
        "area": "Multicanale",
        "task": "Test cross-listing controllato",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Pubblicare pochi articoli su più piattaforme e testare rimozione immediata dopo vendita.",
        "deadline": "Agosto"
      },
      {
        "area": "Prezzi",
        "task": "Regola ribassi 30/60/90 giorni",
        "status": "Da fare",
        "priority": "Media",
        "notes": "Definire quando ribassare, quando cambiare copertina e quando liquidare.",
        "deadline": "Agosto"
      },
      {
        "area": "Settembre",
        "task": "Piano pubblicazione settembre",
        "status": "Da fare",
        "priority": "Alta",
        "notes": "Arrivare a settembre con calendario pubblicazione e almeno 100-200 articoli pronti o in preparazione.",
        "deadline": "Agosto"
      }
    ]
  }
});
